# Generated by Django 2.2.1 on 2019-09-08 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0004_task_author_of_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_text', models.CharField(max_length=200, verbose_name='Название')),
                ('creation_date', models.DateTimeField(verbose_name='Дата создания')),
                ('publication_date', models.DateTimeField(verbose_name='Дата публикации')),
                ('author_of_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_text', models.CharField(max_length=200, verbose_name='Название')),
                ('creation_date', models.DateTimeField(verbose_name='Дата создания')),
                ('publication_date', models.DateTimeField(verbose_name='Дата публикации')),
                ('author_of_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Course', verbose_name='Курс')),
            ],
        ),
        migrations.CreateModel(
            name='LessonTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Lesson', verbose_name='Урок')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Task', verbose_name='Задача')),
            ],
        ),
    ]
